--tuseday 11 oct 2005 19:42:07
--version 1
version›1
add_lable›lable1›File Information›34›29
add_lable›lable2›File Name›5›54
add_lable›lable3›File Size›7›104
add_lable›lable4›File Attributes›6›79
add_lable›lable5›File Last Modification›30›132
add_lable›lable6›Date›7›159
add_lable›lable7›Time›7›183
add_textbox›textbox1›134›51›100
add_textbox›textbox2›134›76›100
add_textbox›textbox3›134›102›100
add_textbox›textbox4›45›156›100
add_textbox›textbox5›46›180›100
add_listview›listview1›249›28›120›180
