--tuseday 11 oct 2005 22:13:30
--version 1
version›1
add_button›button1›Add Menu›10›130
add_button›button2›Add Menu Item›93›130
add_button›button3›Delete Menu›10›157
add_button›button4›Delete Menu Item›120›157
add_lable›lable1›Menu Editer›45›28
add_lable›lable2›Menu›12›63
add_lable›lable3›Menu Item›13›90
add_textbox›textbox1›94›58›100
add_textbox›textbox2›94›86›100
add_listview›listview1›268›34›100›100
add_listview›listview2›379›34›100›100
